### ISSUE TITLE
Replicate `xlwings` column/row/table election with `xlrd` lib

### ISSUE THREAD

**Issue by ankostis** [pandalone/pandalone#1]
Xlwings lib has the very handy [Range.Table](http://docs.xlwings.org/api.html#xlwings.Range.table), `vertical` & `horizontal` props that expand the selection to the right/bottom for as long there are cells with data.

But xlwings relies on Excel's COMServer so it requires the MS app install, so it cannot be used with linux servers, etc. 

We want to replicate this functionality with `xlrd` and `pandas`.
## TASKS
- [x] 1. Read rect-regions
  - [x] 1.1. Ensure dates parsed according to other libs (add TCs).
  - [x] 1.2. Ensure behavior compatible with xlwings.
- [x] 2. Parse Excel refs & urls.
- [ ] 3. Parse json-keywords and process values extracted from excel.
- [ ] 4. Decide how to use xl-refs/urls to build data-trees: 
  - [ ] 4.a. Allow refs in cells instead of values? or
  - [ ] 4.b. allow refs only in specific columns (identified ie by their header?)
- [ ] 5. Impl this excel-->data-dtree functionality with detecting cycles (ie `build_datatree_from_xl()`).

**Comment by ankostis** [comment]
@vinci1it2000 can you check this one?

**Comment by vinci1it2000** [comment]
Ok ;)

**Comment by ankostis** [comment]
Some rough requirements for the high-level URI syntax for an excel-ref:

```
file://D:/folder/file.xlsm#sheet-1!__:A5(mem.bigit=True, xls.type=numpy, init.header=True, pd.columns=['a','b'])
http://some.url.com/folder/file.xlsm#sheet-1!A1
```

The start-end cel refs syntax:

```
A1:B2 --> matrix
A_:B_ --> matrix of non-empty cells in AB columns 
A5:_5 --> row-vector of non-empty cells from A5 
A5:_6 --> matrix of non-empty cells from A5
__:A5 --> matrix of non-empty cells A1:A5
```

or in excel's RC notation:

```
R1C1:R2C2 --> matrix
__C1:__C2 --> matrix of non-empty cells in AB columns
_:R5C1 --> matrix from 1st non-empty cell till A1:A5
```

**Comment by ankostis** [comment]
Some coding tips:
- Reuse pandas code for parsing dates, etc: https://github.com/pydata/pandas/blob/master/pandas/io/excel.py#L322
- See the same function implemented by `openpyxl` lib: https://openpyxl.readthedocs.org/en/latest/_modules/openpyxl/worksheet/iter_worksheet.html#IterableWorksheet

**Comment by ankostis** [comment]
PR #4 is improving.  But we are still we're missing a `parse_xl_url()` that will use the (renamed) `parse_xl_ref()` and augment its returning `dict`.

That `dict`-result will be used by some elaborate datatree building function/class that, among others, should detect cycles.

**Comment by ankostis** [comment]
Recapitulating things: Parsing urls/refs is ok.

Next steps:
1. Ensure dates parsed according to other libs (add TCs).
2. Ensure behavior compatible with xlwings.
3. Decide how to use xl-refs/urls to build data-trees: 
   - Allow refs in cells instead of values? or
   - allow refs only in specific columns (identified ie by their header?)
4. Impl this excel-->data-dtree functionality with detecting cycles (ie `build_datatree_from_xl()`).

**Comment by ankostis** [comment]
Example Quick'n Dirty code for parsing json-onject:

```
types_funcs = {
    None, {},
    'df':
        #'func_kws': 'df_kws',
        'func': pd.DataFrame
}

jsobj = {'type': 'df', 'df_kes'={'heeader':True}, 'filter_func':'convert_num'}

def f(jsobj, types_funcs):
    tp = jsobj.get('type')
    if tp:
        tf = types_funcs.get(tp)
        if tf:
            fkws = tf.get('func_kws')
            if not fkws:
                fkws = '%{}_kws'.format(tp)
            fkws = jsonobj.get(fkws)
            res = tf.['func'](**fkws)

```

**Comment by ankostis** [comment]
## SAMPLE REFS

```
B5       --> bool, string, float, int (IGNORES "DIM")
```

Lists-results::

```
B1:C10   --> 10x2, NOT skipping NaNs 
B1:B10   --> x10, NOT skipping NaNs (even if x1 or [])

B1:B_    --> xEnd, NOT skipping NaNs (even if x1 or []) 
B1:B*    --> x?, skipping NaNs (even if x1 or [])
B1:*1    --> x?, skipping NaNs (even if x1 or [])
B1:B10{"dim":2} --> 
            1x10, NOT skipping NaNs
B1:B*{"dim":0} --> 
            <but might be a value if B1 only nonempty>
B*:B*{"dim":0} --> 
            <but might be a value if only 1 nonempty in B column>
B*:B*{"dim": [0, 0] } --> 
            <like above, but raise if more than 1 value in column!>

B_:C*    --> (list of lists OR list), ?x2, skipping NaNs from top  
B1:C*    -->           <equivalent to the above>  
B*:C*    --> (list of lists or list), ?x2, skipping NaNs from top & bottom  

__:A5    --> (list of lists OR list) of non-empty cells till A1:A5
A1:A5    -->           <equivalent to the above>  
A1:A5    -->           <equivalent to the above>  

A5:**    --> ?x?, skipping NaNs from right & bottom
A5:      -->           <equivalent to the above>  

A1{"dim":2}         --> single value 1x1  
A1:{"dim":2}        -->  ?x?
A1:**{"dim":2}      -->  

: --> **:** 

A1:A1               --> x1
A1:A1{"dim": 0}     --> value
A1:A2{"dim": 0}     --> x2
A1:A2{"dim": [0,0]} --> RAISE!
A1:A*{"dim": [0,0]} --> RAISE if more than a single value in A column
```

Other types::

```
A1{"type":"df"}     --> Single-value df (the same "series" & "nparray")
A1:B2{"type":"df"}  --> 2-column df (the same "series" & "nparray")
A1:B2{"type":"df"}  --> 2-column df (the same "nparray")
```

## JSON_ARGS:

```
jsobj = {
    'type': 'df',  # [ df | nparray | xray.dataset | xray.dataset ]  
    'args':[], 
    'kws': {'header':True},
    'xlwings': True,  # Only affect rect-scanning on 1st row/column.
    'dim': 1, # [ *auto*| 0 | 1 | 2 | ...] OR [ (min, max)!!! 
    'filters':[{
        'type': 'convert_num', 
        'args':[], 
        'kws': {},
        }
    ]
```

`xlwings` flag: 
    `True`:  Only affect rect-scanning on 1st row/column.

`dim` arg: 
    Syntax: `[ *auto*| 0 | 1 | 2 | ...] OR '[' min, max ']'` 
    When single value, it is the min-dim, max is infinite.
    The default value of "dim" is "auto" and means the 
    min-dim equals the dimension of _xl-ref range_ (not of the scanned values!).

**Comment by ankostis** [comment]
# ADDITIONAL SYMBOL and BEHAVIOR

## ALT1:

```
    ?: rect-scan convex & stop on 1st empty- cell of 1st row/col (xlwings)
    *: rect-scan concave 
    +: region-margins
    _: xl-margins
```

## ALT2:

```
    ?: scan region_margins other-cell (denegerate to  
    *: scan from other-cell (denegerate to 
    +: region-margin (degenerates to '_' when region unspecified)
    _: xl-margin
```
- FLAGS:

```
    "scanorder": {"axis1st: ( "row" | "col" ), "cell1st": ( "up" | "down" ) }
    "concave": true | false  ## Whether to attempt to expand identified rect.
```

**Comment by vinci1it2000** [comment]
## IMPOSSIBLE COMBINATIONS

 ??:?? 
 **:**

**Comment by ankostis** [comment]
## Primitive moves

There are 12 "primitive scan-directions" or excel "cell-moves" named with 
a single or a pair of the letters "LURD"::

```
        U
 UL◄───┐▲┌───►UR
LU     │││     RU
 ▲     │││     ▲
 │     │││     │
 └─────┼│┼─────┘
L◄──────X──────►R
 ┌─────┼│┼─────┐
 │     │││     │
 ▼     │││     ▼
LD     │││     RD
 DL◄───┘▼└───►DR
        D

- The 'X' at the center points the starting cell.
```

Using these moves we can identify (or visit) a "target" xl-cell from known 
"starting" cell (ie 'A1', or '__' for the end of the sheet) when the values
visited during the move change from empty to non-empty, and vice versa.

For instance, given this xl-sheet below, here some of the ways 
to identify the non-empty values::

```
  A B C D E F 
1 . . . . . . 
2 . . . . . . 
3 . . X . . .  ──► C3    A1(RD)   _1(LD)     F3(L) 
4 . . . . X .  ──► E4    A4(R)    _4(L)      D1(DR)
5 . X . . . .  ──► B5    A1(DR)   A_(UR)     _5(L) 
6 . . . . . X  ──► F6    __       _1(D)      A_(R) 

- The 'X' signify non-empty cells.
- The dots('.') are empty-cells.
```

So starting cells are specified using "absolute coordinates", using
the usual "A1" notation, expanded with undesrcore('_') which signifies 
the top/bottom rows and left/right columns of the sheet with non-empty values.

After having identified the target "up" cell, we may use "relative" coords 
using the asterisk('*') to identify the "down" cell, specifying thus 
a complete "range".

Of course we _reverse_ the procedure, starting from the down-cell and driving 
relatively to the up-cell. The default direction is "RD".

In the above example-sheet, here are some ways to specify ranges::

```
  A B C D E F 
1 . . . . . . 

2 . . . . . . 
     ┌─────┬──────► C3:E4    A1(RD):**(RD)    _1(RD):**(DR)
3 . .│X . .│ .
   ┌─┼─────┼┐
4 .│.│. . X││.
   │ └─────┘│
5 .│X . . . │.
   └────────┴─────► B4:E5    A_(UR):**(RU)    _5(L):1_(UR)
6 . . . . . X
```

.. NOTE::
   Of course, THE ABOVE WILL FAIL since moves will stop immediately due to empty cells,
but this was to convey the general idea.  Under normal circumstances, 
the in-between cells would be full.

**Comment by vinci1it2000** [comment]
(latest copied from sources @cc2539a)

Implements an "Excel-url" format for capturing ranges from sheets.

# Excel-range addressing ("xl-refs")

## Primitive moves

There are 12 "primitive scan-directions" or excel "cell-moves" named with
a _single_ or a _pair_ of the the letters `"LURD"`::

```
        U
 UL◄───┐▲┌───►UR
LU     │││     RU
 ▲     │││     ▲
 │     │││     │
 └─────┼│┼─────┘
L◄──────X──────►R
 ┌─────┼│┼─────┐
 │     │││     │
 ▼     │││     ▼
LD     │││     RD
 DL◄───┘▼└───►DR
        D

- The 'X' at the center points the starting cell.
```

## Target-cells

Using these moves we can identify a "target" xl-cell from a known
"starting" position (ie `A1`, or `^^` and `__` for the start/end of the sheet) 
when the values visited in the 1st row/column _change_ from empty to non-empty, 
and vice versa.

For instance, given this xl-sheet below, here some of the ways
to identify (or target) the non-empty values `X`::

```
  A B C D E F
1
2
3     X        ──► C3    A1(RD)   _^(L)      F3(L)
4         X    ──► E4    A4(R)    _4(L)      D1(DR)
5   X          ──► B5    A1(DR)   A_(UR)     _5(L)
6           X  ──► F6    __       _^(D)      A_(R)

- The 'X' signify non-empty cells.
```

So we can target cells with "absolute coordinates" (the usual "A1" notation),
expanded with:
- undesrcore(`_`) for bottom/right, and
- accent(`^`) for top/left

columns/rows of the sheet with non-empty values.

When no "LURDS" are specified, the target-cell coinceds with the starting one.

## Ranges

To specify a complete "range" we need to identify a 2nd cell.
The 2nd target-cell may be specified:
- either with absolute coordinates, as above, or
- with "relative" coords, using the dot(`.`) to refer to the 1st cell.

In the above example-sheet, here are some ways to specify ranges::

```
  A  B C D E  F
1              

2              
      ┌─────┐  
   ┌──┼─┐   │  
3  │  │X│   │  
   │┌─┼─┼───┼┐ 
4  ││ │ │  X││ 
   ││ └─┼───┴┼───► C3:E4   A1(RD):..(RD)   _.(RD):..(DR)   _4(L):A1(RD)
5  ││X  │    │ 
   │└───┼────┴───► B4:E5   A_(UR):..(RU)   _5(L):1_(UR)    E1(D):A.(DR)
6  │    │     X
   └────┴────────► Β3:C6   A1(RD):^_       ^^:C_           C_:^^
```

.. Warning::
   Of course, the above ranges WILL FAIL since the range-traversing moves
   will stop immediately due to `X`s being surrounded by empty-cells.

   But the above diagram was to just convey the general idea.
   Under normal circumstances, all the in-between cells must be non-empty.

The required moves for traversing from 1st to 2nd cell are
calculated automatically from the relative positions of the 2 targets cells.
In the case of relative-coords, these moves may or may not concede 
with the moves of the 2nd-cell.

For instance, to capture `B4:E5` in the above sheet we may use `_5(L):E.(U)`.
In that case the target cells are `B5` and `E4` and the traversing-move
to reach the 2nd one is calculated to be `UR` which is different from `U`.

.. Note::
    The traversing-moves from 1st to 2nd target cell will fetch 
    the same values regardless of whether we are traversing "row-first" or 
    "column-first".

## Expansion

Captured rect-ranges ("values") may be limited due to empty-cells in the 
1st row/column.
To overcome this, the xl-ref may specify "expansions" directions using 
a 3rd `:`-section like that::

```
_5(L):1_(UR):RDL?U?
```

This particular case means: 

> Try expanding Right and Down repeatedly and then one Left and Up.

Expansion happens row-by-row or column-by-column basis, and terminates when 
a full empty(or non-empty) line is met.

Example-refs are given below for capturing the 2 marked tables::

```
  A  B C D E F  G
1                
   ┌───────────┐  
   │┌─────────┐│ 
2  ││  1 X X  ││ 
   ││         ││ 
3  ││X X   X X││ 
   ││         ││ 
4  ││X X X 2 X││ 
   ││         ││ 
5  ││X   X X X││ 
   └┼─────────┼┴──► A1(RD):..(RD):DRL?
6   │X        │  
    └─────────┴───► A1(RD):..(RD):L?DR       A_(UR):^^(RD)
7               X

- The 'X' signify non-empty cells.
- The '1' and `2` signify the identified target-cells.
```

**Comment by vinci1it2000** [comment]
## Definitions
- 1st cell: is the cell defined before ':'.
- 2nd cell: is the cell defined after the first ':'.
- cell-moves: are the 12 scan-directions in the parentheses '(...)'.
- cell-row: is the row coordinate of a cell.
- cell-col: is the column coordinate of a cell.
- cell-ref: is a pair of cell row-col coordinates.
- cell-start: is the initial cell ref before the cell moves.
- cell-target: is the final cell ref after the cell moves.
- cell-state: can be empty or full(non-empty).
- relative position: identified with a dot('.') for each cell-coordinate.
  It can be used only in the 2nd cell-start ref (e.g., '.3', '..', 'B.').
  It assumes that:
        2nd cell-start col/row = 1st cell-target col/row
- absolute position: identified with '^' and '_' for each cell-coordinate.
  - '^': upper full cell-coordinate.
  - '_': lower full cell-coordinate.

## Basic search cell-target rules
- search-opposite-state:
  the cell-target is the first cell founded according to the cell-moves that has
  the opposite state of the cell-start.
- Search-same-state:
  the cell-target is evaluated according to the target-coordinate-moves.
  - target-coordinate-move (cell-row if move='L' or 'R', cell-col if move='U' or
    'D') is the last cell founded from the relative start-coordinate according
    to the move that has the same state of the cell-start.

## 1st cell target search

If the 1st-cell:
- has not cell-moves: cell-target = cell-start
- has cell-moves: cell-target is evaluated using the search-opposite-state
    rule.

## 2nd cell target search

If the 2nd-cell:
- has not cell-moves: cell-target = cell-start
- has cell-moves and:
  - 2nd-cell-start-state == 1st-cell-start-state:
    cell-target is evaluated using the search-same-state rule.
  - 2nd-cell-start-state != 1st-cell-start-state:
    cell-target is evaluated using the search-opposite-state rule.

**Comment by ankostis** [comment]
I'm taking over this.
We have still many things here, both behaviorally and in code-quality.

An important note is that ONLY DoctTesting a method, leaves uncovered in Python-2.

For instance while Py3-coverage is 93%, in Py2 is %81, but that is not the whole story.
Coverage does not mean everything checked, just that id does not blow.

**Comment by ankostis** [comment]
Done :-)
